### ISSUE TITLE
事务可用性配置

### ISSUE THREAD

**Issue by Akimotorakiyu** [brickyang/easy-mongodb#10]
mongodb的事务在单节点时候是不能使用的。（直接报错）

但是在生产环境下复制集时候可用。

开发时候就很恶心咯。。。必须配置复制集

**Comment by Akimotorakiyu** [comment]
希望有一个配置，在生产环境下自动事务可用，开发环境下，事务无用。

**Comment by brickyang** [comment]
不太明白你的需求。开发环境不开副本集你怎么写事务代码呢？
