### ISSUE TITLE
有没有例子？每次操作数据库都得connect吗？

### ISSUE THREAD

**Issue by YSHIDM** [brickyang/easy-mongodb#11]
const MongoDB = require('@brickyang/easy-mongodb').default;
const config = {
  host: '127.0.0.1',
  port: '27017',
  name: 'test',
};
const mongo = new MongoDB(config);

async function find() {
  await mongo.connect();//第一次
  let f = await mongo.find('ts');
   console.log(u);
}
find();
async function update() {
  await mongo.connect();//第二次？
  let f = await mongo.update('ts',{{id:1},{age:2}});
   console.log(u);
}
update();

**Comment by YSHIDM** [comment]
为什么
mongoose.connect(DB_URL, { useNewUrlParser: true });
明明是异步的，去不需要 await，不懂。

**Comment by brickyang** [comment]
只需要应用启动时连接一次即可，在没有关闭之前不需要重复连接。

**Comment by YSHIDM** [comment]
每次使用mongo的方法不会调用mongo.connect()方法吗

**Comment by brickyang** [comment]
不需要
