### ISSUE TITLE
Object.freeze 导致 MongoClient 不能 reconnect

### ISSUE THREAD

**Issue by lukeupup** [brickyang/easy-mongodb#12]
use case:
我们在使用 egg-mongo-native 连接 Mongo. 由于不可控原因，与mongo的连接有时会中断，并且超过了 MongoClient 自动重连的次数上限，必须手动重连。

手动重连调用的是 MongoClient 的 [connect](https://mongodb.github.io/node-mongodb-native/3.2/api/MongoClient.html#.connect) 方法，但是调用 connect 的时候出现了以下错误：

TypeError: Cannot assign to read only property 'topology' of object '#<MongoClient>'

经检查，这是由于 easy-mongodb 在连接后把 client 和 db 都 freeze 了，导致 MongoClient 无法正常更新自己的属性。

代码在这里：https://github.com/brickyang/easy-mongodb/blob/master/lib/mongo.js#L76

调用 Db 对象的 on 方法监听事件的时候，同样会由于Object.freeze，无法成功监听：
TypeError: Cannot assign to read only property '_eventsCount' of object '#<Db>'

我不是特别理解这里把 client 和 db 冻结的原因。但是既然可以访问client和db两个对象，建议取消冻结，避免出错。谢谢！

**Comment by brickyang** [comment]
`freeze` 的原因就如其功能，`db` 和 `client` 都应该是只读的而避免从外部被手动修改。

我研究一下你提出的 use case 的情况，但单纯地取消 `freeze` 应该不是解决办法。

p.s. 你试过在第一次连接时提高自动重试的限制吗？

**Comment by lukeupup** [comment]
重连次数我试着提高到 Number.MAX_SAFE_INTEGER，但是这样的话，当 mongo 断开时，如果egg 收到一个请求去 mongo 查数据，mongo client 发现断开了就会一直重连，不会 reject 或者 throw exception。一直到 http client 几分钟后超时。这样用户体验也很糟糕。

我同意这两个对象不应被外部修改，不过用 freeze 看起来太过强力了，导致从内部的修改也无法执行，就得不偿失了。至于如果用户执意要不遵循api地改内部状态，应该由用户自己负责，不然几乎所有 node modules 都要把自己freeze了。

**Comment by brickyang** [comment]
其实「手动调用 `connect` 重连」可能就是一种设计外的用法，因为必须承认我没有多考虑过你提出的情况。对于 easy-mongodb 来说可能更恰当地做法是重新实例化一个 MongoDB 对象；对于 egg-mongo-native 来说暴露 `connect()` 方法本身就是临时性的。

我还在想更合理的解决方法，不是为了保留 `freeze`，而是觉得手动重连有点不对。特别是对其他依赖本库的库来说，这应该是一个异常情况（包括重连和你说的不会 reject），可能都应该由那些库去解决而不是扔给用户。

**Comment by brickyang** [comment]
你可以先提一个删除 `freeze()` 的 PR，或者等我方便时处理。

**Comment by lukeupup** [comment]
PR 有了。手动重连这个事我也感觉不太对，但是 mongodb 的自动重连就像我上面描述的，也很不好用。我觉得合理的行为应该是它重试几次发现连不上之后抛错，但是持续尝试重连，而不是把我的 query 卡在那里。但是查了一下并没有找到 mongodb 有这种设置，不知道是不是忽略了什么。
