### ISSUE TITLE
[Question] 数据类型的设置

### ISSUE THREAD

**Issue by Akimotorakiyu** [brickyang/easy-mongodb#14]
Mongodb本身是有数据类型的，对于数值相关有`timestamp` `double`等，这样就导致一个问题！
我存的时间戳数字被保存成了double类型，在使用`mongoexport`导出时候变成了指数表达形式，而且值都不对了。

请问使用如何
1. 正确的设置保存数据类型
2. 转换已有的数据库的错误数据类型

**Comment by brickyang** [comment]
本包只是对官方 Driver 的包装和扩展，数据类型的问题请参阅 MongoDB 文档。简单来说就是像 ObjectID 一样需要你自己调用 Timestamp 对象。

https://docs.mongodb.com/manual/reference/bson-types/#timestamps
