### ISSUE TITLE
Question: 在分页时候，同时获取分页内的文档和文档总数的正确姿势？

### ISSUE THREAD

**Issue by Akimotorakiyu** [brickyang/easy-mongodb#5]
`find() || find().limit().skip()`在返回结果的时候是不带文档的总文档数的，但是我又需要总文档数，所以我又进行了一次`count()`查询以获得总文档数。

故每次分页，我都进行了两次查询请求。。。

Question: 在分页时候，同时获取分页内的文档和文档总数的正确姿势？

**Comment by brickyang** [comment]
正确姿势就是 `find()` + `count()`。

**Comment by Akimotorakiyu** [comment]
像下面这样？我竟然没写错？
``` javascript
async controller(req,res){
    ...
    let count = count();
    let docs = find();
    await count ;
    await docs;
   ...
}
```

**Comment by brickyang** [comment]
查询和统计本来就是两个动作，MongoDB 的文档暂时没发现有别的说法。

`count()` 已经是 deprecated 状态了。

**Comment by Akimotorakiyu** [comment]
OK!
我将会切换到`countDocuments()`。
